
# docs Makefile
# copied from ../tools/framework/docs/dummies/Makefile 

include ../tools/framework/global-make.mk

init:
	$(mkdir) 3rd-party-docs
	$(mkdir) discussion-notes
	$(mkdir) literature
	$(mkdir) reports
	$(mkdir) reports-compiled
	$(mkdir) service-requests

