
# docs Makefile
# copied from ../tools/framework/docs/dummies/Makefile 

include ../tools/framework/global-make.mk

init: folderstructure
	$(copy)  ../tools/framework/docs/dummies/main-project-readme.md   ../README-project.md

folderstructure: 
	$(mkdir) 3rd-party-docs
	$(mkdir) discussion-notes
	$(mkdir) literature
	$(mkdir) reports-sources
	$(mkdir) reports-compiled
	$(mkdir) service-requests
