variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test


docker-build-main:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "Hello 1"
    - echo "Hello 2"
    - apk add git make
    - echo "Hello 3"
    - git config --global http.sslVerify "false"
    - git submodule init
    - git submodule update --recursive --remote
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "running pipeline on branch.. $CI_COMMIT_BRANCH because of a.. $CI_PIPELINE_SOURCE"
    - docker build --pull --tag "$CI_REGISTRY_IMAGE" docker
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "docker-latest")
      changes:
        - .gitlab-ci.yml
        - docker/**/*


make-test:
  stage: test
  image: ubuntu
  before_script:
    - apt-get update
    - apt-get install -y git
    - apt-get install -y make
    - apt-get install -y python3
  script:
    - echo "running pipeline on branch.. $CI_COMMIT_BRANCH because of a.. $CI_PIPELINE_SOURCE"
    - "make -C ./tests/ gitlab-pipeline"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "master"
  artifacts:
    when: always
    untracked: true
    expire_in: 30 days
    paths:
      - tests/


openfoam-paraview:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - echo "running OpenFOAM-Paraview pipeline on branch.. $CI_COMMIT_BRANCH because of a.. $CI_PIPELINE_SOURCE"
    - git config --global --add safe.directory /builds/sofa-framework/core
    - "make -C ./tests/openfoam-paraview"
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
