
initfolder: 
	../tools/simulation-projects/openFoam/createFolderStructure.py

initfoamsubmodules: 
# todo only if not present and then move to foam make
	make -C ../tools/simulation-projects/openFoam openFoam-modules

