
#################################################################
# system settings
#################################################################


#################################################################
# General user settings
#################################################################


#################################################################
# targets
#################################################################

all: 
	pwd
	echo "dummie output" 

submodules:
	cd tools; git submodule add git@gitlab.com:HS-GM_OpenFOAM/openFoamSetup.git
	cd tools; git submodule add git@gitlab.com:HS-GM_OpenFOAM/OpenFoamScripts.git
