FROM ubuntu:20.04


#   install std utils
# ==========================================================
RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common
RUN apt-get install -y sudo
RUN apt-get install -y wget
RUN apt-get install -y curl
RUN apt-get install -y libglu1
RUN apt-get install -y ca-certificates
RUN apt-get install -y gnupg
RUN apt-get install -y vim
RUN apt-get install -y nano
RUN apt-get install -y git
RUN apt-get install -y make
RUN apt-get install -y nodejs


#   install R reporting tools
# ==========================================================

RUN mkdir -p /scripts
COPY install-r-deb-packages.sh /scripts
COPY install-r-packages.sh /scripts
WORKDIR /scripts
RUN chmod +x install-r-deb-packages.sh
RUN ./install-r-deb-packages.sh
RUN ./install-r-packages.sh
WORKDIR /


#   install OpenFOAM 7
# ==========================================================
RUN sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
RUN add-apt-repository http://dl.openfoam.org/ubuntu
RUN apt-get update
RUN apt-get install -y --no-install-recommends openfoam7

# create separate user with login shell
RUN useradd --user-group --create-home --shell /bin/bash foam ;\
	echo "foam ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER foam
RUN echo "source /opt/openfoam7/etc/bashrc" >> ~foam/.bashrc 
USER root


#   install Paraview
# ==========================================================
# install separate paraview for pvpython inside pvbatch

# download paraview from https://www.paraview.org/download/
ARG  PARAVIEW_VERSION=5.7
ARG  PARAVIEW_DOWNLOAD=ParaView-5.7.0-MPI-Linux-Python3.7-64bit
RUN wget --quiet --output-document - \ 
    "https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v${PARAVIEW_VERSION}&type=binary&os=Linux&downloadFile=${PARAVIEW_DOWNLOAD}.tar.gz"  \
    | tar -xz --directory=/opt  -f - 

# make pvpython and pvbatch available in your $PATH
RUN ln --symbolic /opt/${PARAVIEW_DOWNLOAD}/bin/pvbatch /bin
RUN ln --symbolic /opt/${PARAVIEW_DOWNLOAD}/bin/pvpython /bin



# closing
# ==========================================================

USER foam
WORKDIR /
